// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChTIlTiVbGdQ7vamJn4sW9-_GTL2ro1M',
    appId: '1:996074011655:web:f95dc6cc14e9f05c073ea2',
    messagingSenderId: '996074011655',
    projectId: 'expense-tacking',
    authDomain: 'expense-tacking.firebaseapp.com',
    storageBucket: 'expense-tacking.appspot.com',
    measurementId: 'G-32X759LPDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwO0vlKe0J0WxL8rp4f6xWl6FmqJpjl3o',
    appId: '1:996074011655:android:c3e35589f76c18ec073ea2',
    messagingSenderId: '996074011655',
    projectId: 'expense-tacking',
    storageBucket: 'expense-tacking.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRCZN6rHUCKCw2l0TD0BymK-ARyKyK_s',
    appId: '1:996074011655:ios:15dcc9ea17e7f27b073ea2',
    messagingSenderId: '996074011655',
    projectId: 'expense-tacking',
    storageBucket: 'expense-tacking.firebasestorage.app',
    androidClientId: '996074011655-1b4gsu9nev1lblul0hd8alaqug6hpr49.apps.googleusercontent.com',
    iosClientId: '996074011655-at3j7riomssmpn0qqsuvmt1n967m72ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRCZN6rHUCKCw2l0TD0BymK-ARyKyK_s',
    appId: '1:996074011655:ios:15dcc9ea17e7f27b073ea2',
    messagingSenderId: '996074011655',
    projectId: 'expense-tacking',
    storageBucket: 'expense-tacking.appspot.com',
    androidClientId: '996074011655-1b4gsu9nev1lblul0hd8alaqug6hpr49.apps.googleusercontent.com',
    iosClientId: '996074011655-at3j7riomssmpn0qqsuvmt1n967m72ve.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCChTIlTiVbGdQ7vamJn4sW9-_GTL2ro1M',
    appId: '1:996074011655:web:87ecd1effb579c27073ea2',
    messagingSenderId: '996074011655',
    projectId: 'expense-tacking',
    authDomain: 'expense-tacking.firebaseapp.com',
    storageBucket: 'expense-tacking.appspot.com',
    measurementId: 'G-495LT3G6KN',
  );
}
